name: ipst_test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  app_links: ^6.3.2
  auto_route: ^9.2.2
  collection: ^1.18.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.3.0
  flutter_in_app_pip: ^1.7.4
  flutter_launcher_icons: ^0.14.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_vlc_player: ^7.4.2
  fluttertoast: ^8.2.8
  form_builder_validators: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sample_video.mp4
    - assets/350x150.png
    - assets/camera-loading.json
